// Australian Postcode → Suburb lookup
// Format: "XXXX": [["Suburb","ST"], ...]
// Covers all major population centres across all states and territories.
// Falls back to free-text entry for unlisted postcodes.
const AU_POSTCODES = {
// ── ACT ─────────────────────────────────────────────────────────────────────
"0200":[["Australian National University","ACT"]],
"0221":[["Barton","ACT"]],
"2600":[["Canberra City","ACT"],["Barton","ACT"],["Capital Hill","ACT"],["Parkes","ACT"],["Yarralumla","ACT"]],
"2601":[["Civic","ACT"],["Acton","ACT"],["Turner","ACT"]],
"2602":[["Ainslie","ACT"],["Dickson","ACT"],["Downer","ACT"],["Hackett","ACT"],["Lyneham","ACT"],["O'Connor","ACT"],["Watson","ACT"]],
"2603":[["Deakin","ACT"],["Forrest","ACT"],["Griffith","ACT"],["Yarralumla","ACT"]],
"2604":[["Kingston","ACT"],["Narrabundah","ACT"],["Symonston","ACT"]],
"2605":[["Garran","ACT"],["Hughes","ACT"]],
"2606":[["Chifley","ACT"],["Curtin","ACT"],["Farrer","ACT"],["Mawson","ACT"],["Pearce","ACT"],["Torrens","ACT"]],
"2607":[["Isaacs","ACT"],["Mawson","ACT"],["Phillip","ACT"]],
"2608":[["Acton","ACT"]],
"2609":[["Fyshwick","ACT"],["Pialligo","ACT"],["Symonston","ACT"]],
"2611":[["Chapman","ACT"],["Fisher","ACT"],["Holder","ACT"],["Rivett","ACT"],["Stromlo","ACT"],["Waramanga","ACT"],["Weston","ACT"]],
"2612":[["Campbell","ACT"],["Turner","ACT"]],
"2613":[["Belconnen","ACT"],["Cook","ACT"],["Florey","ACT"],["Flynn","ACT"],["Giralang","ACT"],["Higgins","ACT"],["Holt","ACT"],["Kaleen","ACT"],["Macgregor","ACT"],["Page","ACT"],["Scullin","ACT"]],
"2614":[["Belconnen","ACT"],["Bruce","ACT"],["Evatt","ACT"],["Fraser","ACT"],["Giralang","ACT"],["Hawker","ACT"],["Kaleen","ACT"],["Latham","ACT"],["Macgregor","ACT"],["Weetangera","ACT"]],
"2615":[["Charnwood","ACT"],["Dunlop","ACT"],["Flynn","ACT"],["Fraser","ACT"],["Latham","ACT"],["Macgregor","ACT"],["Melba","ACT"],["Spence","ACT"]],
"2616":[["Gungahlin","ACT"]],
"2617":[["Amaroo","ACT"],["Casey","ACT"],["Franklin","ACT"],["Gungahlin","ACT"],["Harrison","ACT"],["Ngunnawal","ACT"],["Nicholls","ACT"],["Palmerston","ACT"],["Taylor","ACT"]],
"2618":[["Hume","ACT"],["Kowen","ACT"]],

// ── NSW — Sydney Metro ───────────────────────────────────────────────────────
"2000":[["Sydney","NSW"],["Haymarket","NSW"],["The Rocks","NSW"]],
"2007":[["Broadway","NSW"],["Ultimo","NSW"]],
"2008":[["Chippendale","NSW"],["Darlington","NSW"]],
"2009":[["Pyrmont","NSW"],["Ultimo","NSW"]],
"2010":[["Darlinghurst","NSW"],["Surry Hills","NSW"]],
"2011":[["Elizabeth Bay","NSW"],["Kings Cross","NSW"],["Potts Point","NSW"],["Rushcutters Bay","NSW"],["Woolloomooloo","NSW"]],
"2015":[["Alexandria","NSW"],["Beaconsfield","NSW"],["Erskineville","NSW"]],
"2016":[["Redfern","NSW"],["Waterloo","NSW"]],
"2017":[["Waterloo","NSW"],["Zetland","NSW"]],
"2018":[["Botany","NSW"],["Mascot","NSW"],["Rosebery","NSW"]],
"2019":[["Banksmeadow","NSW"],["Botany","NSW"]],
"2020":[["Mascot","NSW"]],
"2021":[["Centennial Park","NSW"],["Kensington","NSW"],["Moore Park","NSW"],["Waverley","NSW"]],
"2022":[["Coogee","NSW"],["South Coogee","NSW"]],
"2023":[["Bellevue Hill","NSW"]],
"2024":[["Bronte","NSW"],["Clovelly","NSW"],["Waverley","NSW"]],
"2025":[["Bondi","NSW"],["Bondi Junction","NSW"],["North Bondi","NSW"]],
"2026":[["Bondi Beach","NSW"],["North Bondi","NSW"],["Rose Bay","NSW"]],
"2027":[["Darling Point","NSW"],["Double Bay","NSW"],["Edgecliff","NSW"],["Point Piper","NSW"]],
"2028":[["Double Bay","NSW"]],
"2029":[["Rose Bay","NSW"]],
"2030":[["Dover Heights","NSW"],["Vaucluse","NSW"],["Watsons Bay","NSW"]],
"2031":[["Clovelly","NSW"],["Coogee","NSW"],["Randwick","NSW"]],
"2032":[["Kensington","NSW"],["Kingsford","NSW"]],
"2033":[["Randwick","NSW"]],
"2034":[["Maroubra","NSW"]],
"2035":[["Maroubra","NSW"],["Pagewood","NSW"]],
"2036":[["La Perouse","NSW"],["Malabar","NSW"],["Maroubra","NSW"],["South Maroubra","NSW"]],
"2037":[["Glebe","NSW"],["Forest Lodge","NSW"]],
"2038":[["Glebe","NSW"]],
"2039":[["Rozelle","NSW"]],
"2040":[["Leichhardt","NSW"],["Lilyfield","NSW"]],
"2041":[["Balmain","NSW"],["Balmain East","NSW"],["Rozelle","NSW"]],
"2042":[["Enmore","NSW"],["Newtown","NSW"]],
"2043":[["Marrickville","NSW"],["Sydenham","NSW"],["Tempe","NSW"]],
"2044":[["St Peters","NSW"],["Sydenham","NSW"],["Tempe","NSW"]],
"2045":[["Abbotsford","NSW"],["Five Dock","NSW"]],
"2046":[["Drummoyne","NSW"],["Rodd Point","NSW"]],
"2047":[["Drummoyne","NSW"],["Hunters Hill","NSW"]],
"2048":[["Petersham","NSW"],["Stanmore","NSW"]],
"2049":[["Dulwich Hill","NSW"],["Marrickville","NSW"]],
"2050":[["Camperdown","NSW"],["Darlington","NSW"]],
"2060":[["Lavender Bay","NSW"],["McMahons Point","NSW"],["North Sydney","NSW"],["Waverton","NSW"]],
"2061":[["Kirribilli","NSW"],["Milsons Point","NSW"]],
"2062":[["Cammeray","NSW"],["Northbridge","NSW"]],
"2063":[["Lane Cove","NSW"],["Longueville","NSW"],["Northwood","NSW"]],
"2064":[["Artarmon","NSW"],["St Leonards","NSW"]],
"2065":[["Crows Nest","NSW"],["Greenwich","NSW"],["Wollstonecraft","NSW"]],
"2066":[["Chatswood West","NSW"],["Lane Cove","NSW"],["Longueville","NSW"],["Northwood","NSW"]],
"2067":[["Chatswood","NSW"]],
"2068":[["Castlecrag","NSW"],["Middle Cove","NSW"],["Northbridge","NSW"],["Willoughby","NSW"]],
"2069":[["Castle Cove","NSW"],["Roseville","NSW"],["Roseville Chase","NSW"]],
"2070":[["East Lindfield","NSW"],["Gordon","NSW"],["Killara","NSW"],["Lindfield","NSW"]],
"2071":[["Killara","NSW"],["Turramurra","NSW"]],
"2072":[["North Turramurra","NSW"],["Pymble","NSW"]],
"2073":[["St Ives","NSW"]],
"2074":[["Cottage Point","NSW"],["Terrey Hills","NSW"]],
"2075":[["St Ives Chase","NSW"],["Wahroonga","NSW"]],
"2076":[["Turramurra","NSW"],["Wahroonga","NSW"]],
"2077":[["Beecroft","NSW"],["Cheltenham","NSW"],["Pennant Hills","NSW"]],
"2079":[["Hornsby","NSW"],["Hornsby Heights","NSW"],["Mount Colah","NSW"]],
"2080":[["Berowra","NSW"],["Mount Kuring-gai","NSW"]],
"2081":[["Berowra Heights","NSW"]],
"2082":[["Berowra","NSW"],["Berowra Waters","NSW"]],
"2085":[["Manly","NSW"],["Manly Vale","NSW"]],
"2086":[["Balgowlah","NSW"],["Fairlight","NSW"],["Manly Vale","NSW"]],
"2087":[["Clontarf","NSW"],["Seaforth","NSW"]],
"2088":[["Mosman","NSW"]],
"2089":[["Cremorne","NSW"],["Cremorne Point","NSW"],["Neutral Bay","NSW"]],
"2090":[["Cremorne","NSW"],["Neutral Bay","NSW"]],
"2092":[["Balgowlah Heights","NSW"],["Seaforth","NSW"]],
"2093":[["Brookvale","NSW"],["Curl Curl","NSW"],["Freshwater","NSW"]],
"2095":[["Manly","NSW"]],
"2096":[["Collaroy","NSW"],["Dee Why","NSW"]],
"2097":[["Collaroy","NSW"],["Wheeler Heights","NSW"]],
"2099":[["Dee Why","NSW"],["Harbord","NSW"]],
"2100":[["Manly","NSW"],["Queenscliff","NSW"]],
"2101":[["Avalon","NSW"],["Palm Beach","NSW"]],
"2102":[["Mona Vale","NSW"],["Narrabeen","NSW"]],
"2103":[["Church Point","NSW"],["Mona Vale","NSW"]],
"2104":[["Bayview","NSW"],["Ingleside","NSW"]],
"2106":[["Newport","NSW"],["Newport Beach","NSW"]],
"2107":[["Avalon","NSW"],["Bilgola","NSW"]],
"2108":[["Bayview","NSW"],["Pittwater","NSW"]],
"2110":[["Hunters Hill","NSW"]],
"2111":[["Meadowbank","NSW"],["Ryde","NSW"]],
"2112":[["Meadowbank","NSW"],["Ryde","NSW"]],
"2113":[["Ermington","NSW"],["Ryde","NSW"]],
"2114":[["Epping","NSW"],["North Epping","NSW"]],
"2115":[["Ryde","NSW"]],
"2116":[["Eastwood","NSW"],["Ryde","NSW"]],
"2117":[["Macquarie Park","NSW"],["Marsfield","NSW"]],
"2118":[["Carlingford","NSW"],["North Rocks","NSW"]],
"2119":[["Parramatta","NSW"],["Westmead","NSW"]],
"2120":[["Pennant Hills","NSW"],["Thornleigh","NSW"]],
"2121":[["Carlingford","NSW"],["Epping","NSW"]],
"2122":[["Burwood Heights","NSW"],["North Rocks","NSW"]],
"2123":[["Parramatta","NSW"]],
"2125":[["West Pennant Hills","NSW"]],
"2126":[["Castle Hill","NSW"],["Cherrybrook","NSW"]],
"2127":[["Homebush","NSW"],["Newington","NSW"],["Sydney Olympic Park","NSW"]],
"2128":[["Silverwater","NSW"]],
"2130":[["Summer Hill","NSW"]],
"2131":[["Ashfield","NSW"]],
"2132":[["Croydon","NSW"]],
"2133":[["Croydon Park","NSW"],["Enfield","NSW"]],
"2134":[["Burwood","NSW"]],
"2135":[["Strathfield","NSW"]],
"2136":[["Burwood Heights","NSW"],["Croydon Park","NSW"],["Strathfield South","NSW"]],
"2137":[["Concord","NSW"]],
"2138":[["Concord","NSW"],["Rhodes","NSW"]],
"2139":[["Mortlake","NSW"],["North Strathfield","NSW"]],
"2140":[["Homebush","NSW"],["Homebush Bay","NSW"],["Rhodes","NSW"]],
"2141":[["Lidcombe","NSW"]],
"2142":[["Granville","NSW"],["South Granville","NSW"]],
"2143":[["Berala","NSW"],["Regents Park","NSW"]],
"2144":[["Auburn","NSW"]],
"2145":[["Greystanes","NSW"],["Pendle Hill","NSW"],["Wentworthville","NSW"]],
"2146":[["Old Toongabbie","NSW"],["Seven Hills","NSW"],["Toongabbie","NSW"]],
"2147":[["Blacktown","NSW"],["Woodcroft","NSW"]],
"2148":[["Arndell Park","NSW"],["Blacktown","NSW"]],
"2149":[["Lalor Park","NSW"],["Seven Hills","NSW"]],
"2150":[["North Parramatta","NSW"],["Parramatta","NSW"]],
"2151":[["North Rocks","NSW"],["North Parramatta","NSW"]],
"2153":[["Baulkham Hills","NSW"],["Castle Hill","NSW"]],
"2154":[["Castle Hill","NSW"]],
"2155":[["Kellyville","NSW"]],
"2156":[["Glenhaven","NSW"],["Kenthurst","NSW"]],
"2157":[["Dural","NSW"]],
"2160":[["Holroyd","NSW"],["Merrylands","NSW"]],
"2161":[["Greystanes","NSW"],["Merrylands","NSW"]],
"2162":[["Smithfield","NSW"]],
"2163":[["Fairfield","NSW"],["Fairfield East","NSW"]],
"2164":[["Bossley Park","NSW"],["Wetherill Park","NSW"]],
"2165":[["Bonnyrigg","NSW"],["Bonnyrigg Heights","NSW"]],
"2166":[["Cabramatta","NSW"],["Warwick Farm","NSW"]],
"2167":[["Casula","NSW"]],
"2168":[["Cartwright","NSW"],["Miller","NSW"]],
"2170":[["Casula","NSW"],["Liverpool","NSW"]],
"2171":[["Lurnea","NSW"],["Moorebank","NSW"]],
"2173":[["Bangor","NSW"],["Woronora","NSW"]],
"2174":[["Milperra","NSW"],["Revesby","NSW"]],
"2176":[["Potts Hill","NSW"],["Villawood","NSW"]],
"2177":[["Cecil Hills","NSW"],["Green Valley","NSW"]],
"2190":[["Bass Hill","NSW"],["Chullora","NSW"],["Greenacre","NSW"]],
"2191":[["Greenacre","NSW"]],
"2192":[["Punchbowl","NSW"]],
"2193":[["Campsie","NSW"],["Canterbury","NSW"]],
"2194":[["Hurlstone Park","NSW"],["Marrickville","NSW"]],
"2195":[["Lakemba","NSW"]],
"2196":[["Punchbowl","NSW"],["Wiley Park","NSW"]],
"2197":[["Bass Hill","NSW"],["Sefton","NSW"]],
"2198":[["Yagoona","NSW"]],
"2199":[["Bankstown","NSW"]],
"2200":[["Bankstown","NSW"],["Greenacre","NSW"]],
"2203":[["Dulwich Hill","NSW"],["Marrickville","NSW"]],
"2204":[["Enmore","NSW"],["Marrickville","NSW"]],
"2205":[["Arncliffe","NSW"],["Wolli Creek","NSW"]],
"2206":[["Clemton Park","NSW"],["Earlwood","NSW"]],
"2207":[["Bexley","NSW"],["Hurstville","NSW"]],
"2208":[["Bexley North","NSW"],["Kingsgrove","NSW"]],
"2209":[["Beverly Hills","NSW"],["Narwee","NSW"]],
"2210":[["Lugarno","NSW"],["Peakhurst","NSW"],["Penshurst","NSW"]],
"2211":[["Padstow","NSW"]],
"2212":[["Padstow","NSW"],["Revesby","NSW"]],
"2213":[["East Hills","NSW"],["Panania","NSW"],["Picnic Point","NSW"]],
"2216":[["Brighton-Le-Sands","NSW"],["Monterey","NSW"],["Ramsgate","NSW"]],
"2217":[["Carlton","NSW"],["Kogarah","NSW"]],
"2218":[["Allawah","NSW"],["Carlton","NSW"],["Hurstville","NSW"]],
"2219":[["Mortdale","NSW"],["Oatley","NSW"]],
"2220":[["Hurstville","NSW"],["Penshurst","NSW"]],
"2221":[["Como","NSW"],["Jannali","NSW"],["Oyster Bay","NSW"],["Sylvania","NSW"]],
"2222":[["Hurstville","NSW"]],
"2223":[["Sutherland","NSW"],["Sylvania","NSW"]],
"2224":[["Kangaroo Point","NSW"],["Sylvania Waters","NSW"],["Taren Point","NSW"]],
"2225":[["Caringbah","NSW"],["Port Hacking","NSW"]],
"2226":[["Caringbah","NSW"],["Miranda","NSW"]],
"2227":[["Gymea","NSW"],["Jannali","NSW"],["Sutherland","NSW"]],
"2228":[["Engadine","NSW"],["Heathcote","NSW"],["Loftus","NSW"]],
"2229":[["Caringbah South","NSW"],["Cronulla","NSW"]],
"2230":[["Bundeena","NSW"],["Cronulla","NSW"],["Maianbar","NSW"]],
"2231":[["Dolls Point","NSW"],["Ramsgate","NSW"],["Sans Souci","NSW"]],
"2232":[["Sutherland","NSW"],["Yarrawarrah","NSW"]],
"2233":[["Engadine","NSW"],["Heathcote","NSW"]],
"2234":[["Bangor","NSW"],["Menai","NSW"],["Woronora","NSW"]],
// ── NSW — Central Coast ──────────────────────────────────────────────────────
"2250":[["East Gosford","NSW"],["Gosford","NSW"]],
"2251":[["Avoca Beach","NSW"],["Copacabana","NSW"]],
"2256":[["Ettalong Beach","NSW"],["Umina Beach","NSW"],["Woy Woy","NSW"]],
"2257":[["Gosford","NSW"],["Green Point","NSW"],["Kariong","NSW"]],
"2258":[["Kanwal","NSW"],["Wyong","NSW"]],
"2259":[["Tuggerah","NSW"],["Wyong","NSW"]],
"2260":[["Erina","NSW"],["Terrigal","NSW"]],
"2261":[["Terrigal","NSW"],["Wamberal","NSW"]],
"2262":[["Blue Haven","NSW"],["Lake Haven","NSW"],["Toukley","NSW"]],
"2263":[["Budgewoi","NSW"],["Halekulani","NSW"]],
"2264":[["Morisset","NSW"]],
"2280":[["Newcastle","NSW"]],
"2281":[["Caves Beach","NSW"],["Swansea","NSW"]],
"2282":[["Belmont","NSW"],["Belmont North","NSW"]],
"2283":[["Warners Bay","NSW"]],
"2284":[["Charlestown","NSW"]],
"2285":[["Adamstown","NSW"],["Glendale","NSW"],["Newcastle","NSW"]],
"2286":[["Redhead","NSW"],["Whitebridge","NSW"]],
"2287":[["Garden Suburb","NSW"],["Kotara","NSW"]],
"2289":[["Broadmeadow","NSW"],["Hamilton","NSW"]],
"2290":[["Belmont","NSW"],["Blacksmiths","NSW"]],
"2291":[["Hamilton","NSW"],["Newcastle","NSW"]],
"2292":[["Broadmeadow","NSW"],["Hamilton North","NSW"]],
"2293":[["Carrington","NSW"],["Tighes Hill","NSW"],["Wickham","NSW"]],
"2296":[["Islington","NSW"],["Mayfield","NSW"]],
"2297":[["Waratah","NSW"]],
"2299":[["Wallsend","NSW"]],
"2300":[["Cooks Hill","NSW"],["Newcastle","NSW"],["The Hill","NSW"]],
"2302":[["Broadmeadow","NSW"],["Mayfield","NSW"]],
"2303":[["Mayfield","NSW"]],
"2304":[["Shortland","NSW"],["Wallsend","NSW"]],
"2305":[["Fletcher","NSW"],["Minmi","NSW"]],
"2306":[["Beresfield","NSW"],["Hexham","NSW"]],
"2307":[["Callaghan","NSW"],["Jesmond","NSW"],["Kotara","NSW"]],
// ── NSW — Hunter / Port Stephens ─────────────────────────────────────────────
"2315":[["Anna Bay","NSW"],["Boat Harbour","NSW"]],
"2316":[["Corlette","NSW"],["Fingal Bay","NSW"]],
"2317":[["Salamander Bay","NSW"],["Shoal Bay","NSW"]],
"2320":[["East Maitland","NSW"],["Maitland","NSW"],["Rutherford","NSW"]],
"2321":[["Bellbird","NSW"],["Cessnock","NSW"]],
"2322":[["Branxton","NSW"],["Cessnock","NSW"]],
"2323":[["Maitland","NSW"],["Thornton","NSW"]],
"2325":[["Cessnock","NSW"]],
"2326":[["Kurri Kurri","NSW"]],
"2328":[["Muswellbrook","NSW"]],
"2329":[["Singleton","NSW"]],
"2330":[["East Maitland","NSW"],["Maitland","NSW"]],
// ── NSW — Regional ───────────────────────────────────────────────────────────
"2340":[["South Tamworth","NSW"],["Tamworth","NSW"]],
"2350":[["Armidale","NSW"]],
"2360":[["Inverell","NSW"]],
"2370":[["Glen Innes","NSW"]],
"2380":[["Moree","NSW"]],
"2390":[["Narrabri","NSW"]],
"2444":[["Port Macquarie","NSW"]],
"2450":[["Coffs Harbour","NSW"]],
"2460":[["Grafton","NSW"]],
"2480":[["Lismore","NSW"]],
"2481":[["Byron Bay","NSW"]],
"2482":[["Bangalow","NSW"]],
"2485":[["Tweed Heads","NSW"]],
"2486":[["Banora Point","NSW"],["Tweed Heads South","NSW"]],
"2487":[["Kingscliff","NSW"]],
"2489":[["Cabarita Beach","NSW"],["Pottsville","NSW"]],
// ── NSW — Illawarra / South Coast ────────────────────────────────────────────
"2500":[["Wollongong","NSW"]],
"2502":[["Coniston","NSW"],["Figtree","NSW"],["Gwynneville","NSW"]],
"2505":[["Port Kembla","NSW"]],
"2506":[["Barrack Heights","NSW"],["Warilla","NSW"],["Windang","NSW"]],
"2515":[["Corrimal","NSW"],["Woonona","NSW"]],
"2516":[["Bulli","NSW"],["Woonona","NSW"]],
"2517":[["Austinmer","NSW"],["Thirroul","NSW"]],
"2518":[["Helensburgh","NSW"],["Stanwell Tops","NSW"]],
"2519":[["Figtree","NSW"],["Unanderra","NSW"]],
"2527":[["Albion Park","NSW"],["Shellharbour","NSW"],["Warilla","NSW"]],
"2528":[["Barrack Point","NSW"],["Shellharbour","NSW"]],
"2529":[["Shellharbour","NSW"]],
"2530":[["Dapto","NSW"],["Kembla Grange","NSW"]],
"2535":[["Bomaderry","NSW"],["Nowra","NSW"]],
"2540":[["Nowra","NSW"],["Shoalhaven Heads","NSW"]],
"2545":[["Batemans Bay","NSW"]],
"2546":[["Moruya","NSW"]],
"2550":[["Merimbula","NSW"]],
// ── NSW — ACT Region / Canberra surrounds ────────────────────────────────────
"2580":[["Goulburn","NSW"]],
"2640":[["Albury","NSW"]],
"2641":[["Albury","NSW"]],
"2650":[["Wagga Wagga","NSW"]],
"2660":[["Griffith","NSW"]],
"2680":[["Broken Hill","NSW"]],
"2700":[["Narrandera","NSW"]],
"2710":[["Deniliquin","NSW"]],
"2730":[["Tumut","NSW"]],
// ── VIC — Melbourne Metro ────────────────────────────────────────────────────
"3000":[["Melbourne","VIC"],["South Wharf","VIC"]],
"3002":[["East Melbourne","VIC"],["Richmond","VIC"]],
"3003":[["West Melbourne","VIC"]],
"3004":[["Melbourne","VIC"],["South Yarra","VIC"]],
"3006":[["South Bank","VIC"],["South Wharf","VIC"]],
"3008":[["Docklands","VIC"],["Waterfront City","VIC"]],
"3011":[["Footscray","VIC"],["Seddon","VIC"],["Yarraville","VIC"]],
"3012":[["Brooklyn","VIC"],["Newport","VIC"],["Spotswood","VIC"]],
"3013":[["Williamstown","VIC"]],
"3015":[["Newport","VIC"],["Williamstown","VIC"]],
"3016":[["Williamstown","VIC"]],
"3018":[["Altona","VIC"],["Laverton","VIC"]],
"3019":[["Altona","VIC"],["Brooklyn","VIC"]],
"3020":[["Braybrook","VIC"],["Sunshine","VIC"]],
"3021":[["Kealba","VIC"],["Sunshine North","VIC"]],
"3022":[["Deer Park","VIC"],["Sunshine West","VIC"]],
"3023":[["Cairnlea","VIC"],["Delahey","VIC"],["Kings Park","VIC"]],
"3024":[["Hoppers Crossing","VIC"],["Wyndham Vale","VIC"]],
"3025":[["Altona Meadows","VIC"],["Laverton","VIC"]],
"3026":[["Altona North","VIC"]],
"3028":[["Laverton North","VIC"],["Williams Landing","VIC"]],
"3029":[["Hoppers Crossing","VIC"],["Werribee","VIC"]],
"3030":[["Hoppers Crossing","VIC"],["Wyndham Vale","VIC"]],
"3031":[["Flemington","VIC"],["Kensington","VIC"]],
"3032":[["Ascot Vale","VIC"],["Maribyrnong","VIC"],["Moonee Vale","VIC"]],
"3033":[["Keilor East","VIC"],["Niddrie","VIC"]],
"3034":[["Airport West","VIC"],["Keilor Park","VIC"]],
"3036":[["Keilor","VIC"],["Keilor North","VIC"]],
"3037":[["Calder Park","VIC"],["Taylors Lakes","VIC"]],
"3038":[["Keilor Downs","VIC"],["Taylors Lakes","VIC"]],
"3039":[["Moonee Ponds","VIC"]],
"3040":[["Essendon","VIC"],["Essendon North","VIC"]],
"3041":[["Essendon North","VIC"]],
"3042":[["Airport West","VIC"],["Essendon North","VIC"],["Keilor Park","VIC"]],
"3043":[["Glenroy","VIC"],["Hadfield","VIC"],["Oak Park","VIC"]],
"3044":[["Pascoe Vale","VIC"],["Pascoe Vale South","VIC"]],
"3045":[["Melbourne Airport","VIC"],["Tullamarine","VIC"]],
"3046":[["Coburg North","VIC"],["Glenroy","VIC"]],
"3047":[["Broadmeadows","VIC"],["Campbellfield","VIC"],["Coolaroo","VIC"]],
"3048":[["Campbellfield","VIC"],["Craigieburn","VIC"]],
"3049":[["Meadow Heights","VIC"]],
"3051":[["Hotham Hill","VIC"],["North Melbourne","VIC"]],
"3052":[["Parkville","VIC"]],
"3053":[["Carlton","VIC"]],
"3054":[["Carlton North","VIC"]],
"3055":[["Brunswick","VIC"],["Moonee Ponds","VIC"]],
"3056":[["Brunswick","VIC"]],
"3057":[["Brunswick East","VIC"]],
"3058":[["Coburg","VIC"]],
"3059":[["Campbellfield","VIC"],["Coburg North","VIC"],["Somerton","VIC"]],
"3060":[["Fawkner","VIC"]],
"3061":[["Reservoir","VIC"]],
"3062":[["Reservoir","VIC"]],
"3063":[["Reservoir","VIC"]],
"3065":[["Fitzroy","VIC"]],
"3066":[["Collingwood","VIC"]],
"3067":[["Abbotsford","VIC"]],
"3068":[["Clifton Hill","VIC"],["Fitzroy North","VIC"]],
"3070":[["Northcote","VIC"]],
"3071":[["Thornbury","VIC"]],
"3072":[["Preston","VIC"]],
"3073":[["Preston","VIC"],["Reservoir","VIC"]],
"3074":[["Bundoora","VIC"],["Mill Park","VIC"]],
"3075":[["Lalor","VIC"]],
"3076":[["Doreen","VIC"],["Mernda","VIC"]],
"3078":[["Alphington","VIC"],["Fairfield","VIC"]],
"3079":[["Ivanhoe","VIC"],["Ivanhoe East","VIC"]],
"3081":[["Heidelberg","VIC"],["Heidelberg Heights","VIC"],["Heidelberg West","VIC"]],
"3082":[["Bundoora","VIC"],["Macleod","VIC"]],
"3083":[["Bundoora","VIC"],["Kingsbury","VIC"]],
"3084":[["Rosanna","VIC"],["Viewbank","VIC"]],
"3085":[["Macleod","VIC"],["Yallambie","VIC"]],
"3086":[["Greensborough","VIC"]],
"3087":[["Watsonia","VIC"]],
"3088":[["Eltham","VIC"],["Montmorency","VIC"]],
"3089":[["Eltham North","VIC"]],
"3094":[["Warrandyte","VIC"]],
"3095":[["Diamond Creek","VIC"],["Greensborough","VIC"]],
"3096":[["Diamond Creek","VIC"]],
"3099":[["Hurstbridge","VIC"],["St Andrews","VIC"]],
"3101":[["Kew","VIC"]],
"3102":[["Kew East","VIC"]],
"3103":[["Balwyn","VIC"],["Balwyn North","VIC"]],
"3104":[["Balwyn","VIC"],["Balwyn North","VIC"]],
"3105":[["Bulleen","VIC"],["Templestowe Lower","VIC"]],
"3106":[["Templestowe","VIC"],["Templestowe Lower","VIC"]],
"3107":[["Doncaster","VIC"]],
"3108":[["Doncaster East","VIC"]],
"3109":[["Box Hill North","VIC"],["Doncaster East","VIC"]],
"3121":[["Richmond","VIC"]],
"3122":[["Hawthorn","VIC"],["Hawthorn East","VIC"]],
"3123":[["Hawthorn East","VIC"]],
"3124":[["Camberwell","VIC"],["Canterbury","VIC"]],
"3125":[["Camberwell","VIC"]],
"3126":[["Canterbury","VIC"],["Surrey Hills","VIC"]],
"3127":[["Box Hill","VIC"],["Box Hill South","VIC"],["Surrey Hills","VIC"]],
"3128":[["Box Hill","VIC"],["Box Hill South","VIC"]],
"3129":[["Box Hill","VIC"],["Box Hill South","VIC"]],
"3130":[["Blackburn","VIC"],["Nunawading","VIC"]],
"3131":[["Blackburn North","VIC"],["Nunawading","VIC"]],
"3132":[["Nunawading","VIC"],["Vermont South","VIC"]],
"3133":[["Vermont","VIC"],["Vermont South","VIC"]],
"3134":[["Ringwood","VIC"],["Ringwood North","VIC"]],
"3135":[["Ringwood East","VIC"]],
"3136":[["Croydon","VIC"],["Croydon North","VIC"]],
"3137":[["Kilsyth","VIC"],["Mooroolbark","VIC"]],
"3138":[["Bayswater","VIC"],["Bayswater North","VIC"]],
"3139":[["Boronia","VIC"],["The Basin","VIC"]],
"3140":[["Lilydale","VIC"]],
"3141":[["South Yarra","VIC"],["Toorak","VIC"]],
"3142":[["Hawksburn","VIC"],["Prahran","VIC"],["Windsor","VIC"]],
"3143":[["Armadale","VIC"],["Malvern East","VIC"]],
"3144":[["Malvern","VIC"]],
"3145":[["Caulfield East","VIC"],["Caulfield South","VIC"],["Malvern East","VIC"]],
"3146":[["Glen Iris","VIC"],["Kooyong","VIC"]],
"3147":[["Ashburton","VIC"],["Camberwell","VIC"]],
"3148":[["Ashburton","VIC"],["Chadstone","VIC"]],
"3149":[["Glen Waverley","VIC"],["Murrumbeena","VIC"]],
"3150":[["Glen Waverley","VIC"]],
"3151":[["Burwood East","VIC"],["Forest Hill","VIC"]],
"3152":[["Wantirna","VIC"],["Wantirna South","VIC"]],
"3153":[["Bayswater","VIC"],["Bayswater North","VIC"]],
"3154":[["The Basin","VIC"]],
"3155":[["Ferntree Gully","VIC"]],
"3156":[["Ferntree Gully","VIC"],["Upper Ferntree Gully","VIC"]],
"3158":[["Belgrave","VIC"]],
"3160":[["Emerald","VIC"]],
"3161":[["Caulfield South","VIC"],["St Kilda East","VIC"]],
"3162":[["Caulfield","VIC"],["Caulfield East","VIC"]],
"3163":[["Bentleigh East","VIC"],["Carnegie","VIC"]],
"3165":[["Clarinda","VIC"],["Oakleigh","VIC"]],
"3166":[["Oakleigh South","VIC"]],
"3167":[["Clayton South","VIC"],["Oakleigh","VIC"]],
"3168":[["Clayton","VIC"]],
"3169":[["Clayton South","VIC"]],
"3170":[["Mulgrave","VIC"],["Notting Hill","VIC"]],
"3171":[["Springvale","VIC"],["Springvale South","VIC"]],
"3172":[["Dingley Village","VIC"],["Springvale South","VIC"]],
"3173":[["Keysborough","VIC"],["Springvale South","VIC"]],
"3174":[["Keysborough","VIC"],["Noble Park","VIC"]],
"3175":[["Dandenong","VIC"],["Dandenong North","VIC"]],
"3176":[["Scoresby","VIC"],["Wantirna South","VIC"]],
"3178":[["Rowville","VIC"]],
"3179":[["Scoresby","VIC"]],
"3180":[["Ferntree Gully","VIC"]],
"3181":[["Prahran","VIC"],["Windsor","VIC"]],
"3182":[["St Kilda","VIC"]],
"3183":[["Balaclava","VIC"],["St Kilda East","VIC"]],
"3184":[["Brighton","VIC"],["Brighton East","VIC"]],
"3185":[["Brighton","VIC"],["Gardenvale","VIC"]],
"3186":[["Brighton","VIC"],["Brighton East","VIC"]],
"3187":[["Hampton","VIC"],["Hampton East","VIC"]],
"3188":[["Brighton East","VIC"],["Sandringham","VIC"]],
"3189":[["Highett","VIC"],["Moorabbin","VIC"]],
"3190":[["Highett","VIC"],["Mentone","VIC"]],
"3191":[["Mentone","VIC"],["Parkdale","VIC"]],
"3192":[["Chelsea","VIC"],["Mordialloc","VIC"]],
"3193":[["Beaumaris","VIC"],["Cheltenham","VIC"]],
"3194":[["Aspendale","VIC"],["Chelsea","VIC"],["Edithvale","VIC"]],
"3195":[["Carrum","VIC"],["Patterson Lakes","VIC"],["Seaford","VIC"]],
"3196":[["Carrum Downs","VIC"],["Frankston","VIC"]],
"3197":[["Frankston","VIC"],["Frankston North","VIC"]],
"3198":[["Frankston","VIC"],["Seaford","VIC"]],
"3199":[["Carrum Downs","VIC"],["Langwarrin","VIC"]],
"3200":[["Frankston","VIC"],["Langwarrin","VIC"]],
"3202":[["Cranbourne","VIC"]],
"3204":[["Mornington","VIC"]],
"3205":[["Port Melbourne","VIC"],["South Melbourne","VIC"]],
"3206":[["Albert Park","VIC"],["Middle Park","VIC"],["Port Melbourne","VIC"]],
"3207":[["Port Melbourne","VIC"],["South Melbourne","VIC"]],
// ── VIC — Geelong ────────────────────────────────────────────────────────────
"3210":[["Geelong","VIC"],["South Geelong","VIC"]],
"3212":[["Corio","VIC"],["Norlane","VIC"]],
"3215":[["Corio","VIC"],["Geelong West","VIC"],["Norlane","VIC"]],
"3216":[["Belmont","VIC"],["Grovedale","VIC"]],
"3217":[["Highton","VIC"],["Waurn Ponds","VIC"]],
"3218":[["Geelong West","VIC"]],
"3220":[["Geelong","VIC"]],
"3221":[["Bannockburn","VIC"],["Lethbridge","VIC"]],
"3222":[["Clifton Springs","VIC"],["Drysdale","VIC"]],
"3223":[["Barwon Heads","VIC"],["Ocean Grove","VIC"]],
"3224":[["Barwon Heads","VIC"],["Ocean Grove","VIC"]],
"3225":[["Point Lonsdale","VIC"],["Queenscliff","VIC"]],
"3228":[["Jan Juc","VIC"],["Torquay","VIC"]],
"3229":[["Anglesea","VIC"]],
"3231":[["Lorne","VIC"]],
"3249":[["Colac","VIC"]],
// ── VIC — Ballarat ────────────────────────────────────────────────────────────
"3350":[["Ballarat","VIC"],["Ballarat Central","VIC"]],
"3351":[["Ballarat","VIC"]],
"3352":[["Ballarat","VIC"]],
"3353":[["Ballarat","VIC"]],
"3354":[["Ballarat","VIC"]],
"3355":[["Ballarat","VIC"]],
"3356":[["Ballarat","VIC"],["Sebastopol","VIC"]],
// ── VIC — Bendigo ─────────────────────────────────────────────────────────────
"3550":[["Bendigo","VIC"]],
"3551":[["Bendigo","VIC"]],
"3555":[["Bendigo","VIC"],["Eaglehawk","VIC"]],
"3556":[["Kangaroo Flat","VIC"],["White Hills","VIC"]],
"3557":[["Huntly","VIC"],["Strathfieldsaye","VIC"]],
// ── VIC — Shepparton / Wangaratta / Albury Region ────────────────────────────
"3564":[["Echuca","VIC"]],
"3565":[["Echuca","VIC"]],
"3570":[["Shepparton","VIC"]],
"3580":[["Swan Hill","VIC"]],
"3590":[["Cobram","VIC"]],
"3629":[["Shepparton","VIC"]],
"3630":[["Shepparton","VIC"]],
"3631":[["Mooroopna","VIC"]],
"3666":[["Wangaratta","VIC"]],
"3669":[["Benalla","VIC"]],
"3670":[["Benalla","VIC"]],
"3675":[["Milawa","VIC"],["Wangaratta","VIC"]],
"3676":[["Wodonga","VIC"]],
"3677":[["Wodonga","VIC"]],
"3680":[["Wodonga","VIC"]],
"3690":[["Wodonga","VIC"]],
// ── VIC — Mornington Peninsula ────────────────────────────────────────────────
"3911":[["Somerville","VIC"],["Tyabb","VIC"]],
"3912":[["Baxter","VIC"],["Pearcedale","VIC"]],
"3913":[["Somerville","VIC"]],
"3915":[["Pearcedale","VIC"]],
"3919":[["Hastings","VIC"],["Somerville","VIC"]],
"3920":[["Hastings","VIC"]],
"3922":[["Cowes","VIC"],["Rhyll","VIC"]],
"3923":[["Cowes","VIC"]],
"3926":[["Balnarring","VIC"],["Shoreham","VIC"]],
"3927":[["Main Ridge","VIC"],["Red Hill","VIC"]],
"3930":[["Frankston South","VIC"],["Sorrento","VIC"]],
"3934":[["Blairgowrie","VIC"],["Sorrento","VIC"]],
"3936":[["Portsea","VIC"],["Sorrento","VIC"]],
"3937":[["Portsea","VIC"]],
"3938":[["Rye","VIC"]],
"3939":[["Capel Sound","VIC"],["Rosebud","VIC"]],
"3940":[["Rye","VIC"],["Tootgarook","VIC"]],
"3941":[["Rosebud","VIC"],["Rosebud West","VIC"]],
"3942":[["Dromana","VIC"],["Safety Beach","VIC"]],
"3944":[["Mount Eliza","VIC"],["Mornington","VIC"]],
"3945":[["Mornington","VIC"]],
// ── VIC — Latrobe Valley / Sale / Bairnsdale ─────────────────────────────────
"3825":[["Moe","VIC"]],
"3840":[["Morwell","VIC"]],
"3842":[["Traralgon","VIC"]],
"3844":[["Sale","VIC"],["Stratford","VIC"]],
"3850":[["Sale","VIC"]],
"3860":[["Bairnsdale","VIC"]],
"3875":[["Bairnsdale","VIC"],["Eagle Point","VIC"]],
"3904":[["Lakes Entrance","VIC"]],
// ── VIC — Outer Suburbs / Growth Corridors ────────────────────────────────────
"3750":[["South Morang","VIC"],["Whittlesea","VIC"]],
"3752":[["Doreen","VIC"],["South Morang","VIC"]],
"3753":[["Doreen","VIC"]],
"3754":[["Doreen","VIC"]],
"3755":[["Mernda","VIC"]],
"3756":[["Wallan","VIC"]],
"3757":[["Beveridge","VIC"],["Kinglake","VIC"]],
"3765":[["Mooroolbark","VIC"]],
"3770":[["Lilydale","VIC"]],
"3775":[["Healesville","VIC"]],
"3777":[["Marysville","VIC"]],
"3780":[["Ferny Creek","VIC"]],
"3781":[["Belgrave","VIC"]],
"3782":[["Gembrook","VIC"]],
"3783":[["Emerald","VIC"]],
"3785":[["Upwey","VIC"]],
"3787":[["Belgrave South","VIC"]],
"3800":[["Clayton","VIC"],["Monash University","VIC"]],
"3802":[["Hallam","VIC"],["Lynbrook","VIC"]],
"3803":[["Hallam","VIC"],["Hampton Park","VIC"]],
"3804":[["Hampton Park","VIC"]],
"3805":[["Beaconsfield Upper","VIC"],["Berwick","VIC"]],
"3806":[["Beaconsfield","VIC"],["Berwick","VIC"]],
"3807":[["Berwick","VIC"]],
"3808":[["Pakenham","VIC"]],
"3809":[["Pakenham","VIC"]],
"3810":[["Pakenham","VIC"]],
"3816":[["Drouin","VIC"]],
"3820":[["Warragul","VIC"]],
"3977":[["Botanic Ridge","VIC"],["Cranbourne","VIC"]],
"3978":[["Cranbourne South","VIC"],["Pearcedale","VIC"]],
"3980":[["Clyde","VIC"],["Clyde North","VIC"],["Cranbourne East","VIC"]],
// ── VIC — Mildura ─────────────────────────────────────────────────────────────
"3500":[["Mildura","VIC"]],
"3501":[["Mildura","VIC"]],
"3502":[["Mildura","VIC"]],
"3505":[["Mildura","VIC"]],
// ── VIC — Warrnambool ─────────────────────────────────────────────────────────
"3280":[["Warrnambool","VIC"]],
"3281":[["Warrnambool","VIC"]],
// ── QLD — Brisbane Metro ─────────────────────────────────────────────────────
"4000":[["Brisbane City","QLD"],["Spring Hill","QLD"]],
"4005":[["Bowen Hills","QLD"],["New Farm","QLD"]],
"4006":[["Fortitude Valley","QLD"],["New Farm","QLD"]],
"4007":[["Ascot","QLD"],["Hamilton","QLD"]],
"4008":[["Eagle Farm","QLD"],["Pinkenba","QLD"]],
"4009":[["Brisbane Airport","QLD"],["Eagle Farm","QLD"]],
"4010":[["Albion","QLD"],["Kalinga","QLD"],["Lutwyche","QLD"]],
"4011":[["Clayfield","QLD"],["Hendra","QLD"]],
"4012":[["Nundah","QLD"],["Wavell Heights","QLD"],["Northgate","QLD"]],
"4013":[["Banyo","QLD"],["Nudgee","QLD"]],
"4014":[["Brighton","QLD"],["Deagon","QLD"],["Sandgate","QLD"]],
"4017":[["Bracken Ridge","QLD"],["Brighton","QLD"],["Deagon","QLD"]],
"4018":[["Bracken Ridge","QLD"],["Brighton","QLD"]],
"4019":[["Redcliffe","QLD"],["Margate","QLD"]],
"4020":[["Margate","QLD"],["Woody Point","QLD"]],
"4021":[["Petrie","QLD"],["Redcliffe","QLD"]],
"4022":[["Clontarf","QLD"],["Kippa-Ring","QLD"],["Rothwell","QLD"]],
"4025":[["Moreton Island","QLD"]],
"4030":[["Lutwyche","QLD"],["Windsor","QLD"],["Wooloowin","QLD"]],
"4031":[["Chermside","QLD"],["Gordon Park","QLD"],["Kedron","QLD"]],
"4032":[["Chermside","QLD"],["Chermside West","QLD"]],
"4034":[["Aspley","QLD"],["Boondall","QLD"],["Zillmere","QLD"]],
"4035":[["Albany Creek","QLD"],["Aspley","QLD"],["Bridgeman Downs","QLD"]],
"4036":[["Bald Hills","QLD"],["Bracken Ridge","QLD"]],
"4037":[["Eatons Hill","QLD"]],
"4051":[["Alderley","QLD"],["Enoggera","QLD"],["Gaythorne","QLD"],["Newmarket","QLD"]],
"4053":[["Everton Hills","QLD"],["Everton Park","QLD"],["McDowall","QLD"]],
"4054":[["Arana Hills","QLD"],["Keperra","QLD"]],
"4055":[["Ferny Grove","QLD"],["Ferny Hills","QLD"]],
"4059":[["Kelvin Grove","QLD"],["Red Hill","QLD"]],
"4060":[["Paddington","QLD"]],
"4061":[["Bardon","QLD"],["Ashgrove","QLD"]],
"4064":[["Milton","QLD"],["Petrie Terrace","QLD"]],
"4065":[["Auchenflower","QLD"],["Toowong","QLD"]],
"4066":[["Indooroopilly","QLD"],["Taringa","QLD"]],
"4067":[["St Lucia","QLD"],["Toowong","QLD"]],
"4068":[["Chapel Hill","QLD"],["Fig Tree Pocket","QLD"],["Indooroopilly","QLD"]],
"4069":[["Chapel Hill","QLD"],["Kenmore","QLD"],["Kenmore Hills","QLD"]],
"4070":[["Brookfield","QLD"],["Pullenvale","QLD"]],
"4073":[["Darra","QLD"],["Oxley","QLD"],["Richlands","QLD"]],
"4074":[["Durack","QLD"],["Inala","QLD"],["Sumner","QLD"]],
"4075":[["Corinda","QLD"],["Graceville","QLD"],["Sherwood","QLD"],["Westlake","QLD"]],
"4076":[["Doolandella","QLD"],["Forest Lake","QLD"],["Inala","QLD"]],
"4077":[["Doolandella","QLD"],["Forest Lake","QLD"],["Inala","QLD"],["Oxley","QLD"]],
"4078":[["Inala","QLD"],["Richlands","QLD"]],
"4101":[["South Brisbane","QLD"],["West End","QLD"],["Highgate Hill","QLD"]],
"4102":[["Dutton Park","QLD"],["Woolloongabba","QLD"]],
"4103":[["Annerley","QLD"],["Fairfield","QLD"]],
"4104":[["Yeronga","QLD"],["Tennyson","QLD"]],
"4105":[["Moorooka","QLD"],["Salisbury","QLD"],["Yeerongpilly","QLD"]],
"4106":[["MacGregor","QLD"],["Robertson","QLD"],["Salisbury","QLD"]],
"4107":[["Rocklea","QLD"],["Coopers Plains","QLD"]],
"4108":[["Acacia Ridge","QLD"],["Coopers Plains","QLD"]],
"4109":[["Macgregor","QLD"],["Nathan","QLD"],["Robertson","QLD"],["Sunnybank","QLD"]],
"4110":[["Algester","QLD"],["Sunnybank Hills","QLD"]],
"4111":[["Nathan","QLD"],["Griffith University","QLD"]],
"4112":[["Kuraby","QLD"],["Runcorn","QLD"]],
"4113":[["Eight Mile Plains","QLD"],["Upper Mount Gravatt","QLD"]],
"4114":[["Logan Central","QLD"],["Woodridge","QLD"]],
"4115":[["Runcorn","QLD"]],
"4116":[["Kuraby","QLD"],["Runcorn","QLD"]],
"4117":[["Berrinba","QLD"],["Karawatha","QLD"]],
"4118":[["Forest Lake","QLD"],["Pallara","QLD"],["Parkinson","QLD"]],
"4119":[["Eight Mile Plains","QLD"],["Macgregor","QLD"]],
"4120":[["Greenslopes","QLD"],["Stones Corner","QLD"],["Holland Park","QLD"]],
"4121":[["Holland Park","QLD"],["Holland Park West","QLD"],["Tarragindi","QLD"]],
"4122":[["Mount Gravatt","QLD"],["Mount Gravatt East","QLD"],["Mansfield","QLD"]],
"4123":[["Mackenzie","QLD"],["Rochedale","QLD"],["Wishart","QLD"]],
"4124":[["Daisy Hill","QLD"],["Springwood","QLD"],["Slacks Creek","QLD"]],
"4125":[["Springwood","QLD"]],
"4127":[["Underwood","QLD"],["Stretton","QLD"]],
"4128":[["Cornubia","QLD"],["Loganholme","QLD"]],
"4129":[["Loganholme","QLD"],["Tanah Merah","QLD"]],
"4130":[["Carbrook","QLD"],["Loganholme","QLD"]],
"4131":[["Beenleigh","QLD"],["Logan Village","QLD"]],
"4132":[["Logan Central","QLD"],["Woodridge","QLD"]],
"4133":[["Crestmead","QLD"],["Kingston","QLD"]],
"4151":[["Coorparoo","QLD"],["Greenslopes","QLD"]],
"4152":[["Camp Hill","QLD"],["Coorparoo","QLD"],["Carindale","QLD"]],
"4153":[["Carindale","QLD"]],
"4154":[["Gumdale","QLD"],["Wakerley","QLD"]],
"4155":[["Chandler","QLD"],["Capalaba","QLD"]],
"4156":[["Capalaba","QLD"],["Sheldon","QLD"]],
"4157":[["Birkdale","QLD"],["Wellington Point","QLD"]],
"4158":[["Thorneside","QLD"],["Wynnum West","QLD"]],
"4159":[["Birkdale","QLD"]],
"4160":[["Wynnum","QLD"]],
"4161":[["Wynnum","QLD"],["Wynnum West","QLD"]],
"4163":[["Cleveland","QLD"],["Thornlands","QLD"]],
"4164":[["Alexandra Hills","QLD"],["Cleveland","QLD"]],
"4165":[["Ormiston","QLD"],["Redland Bay","QLD"],["Victoria Point","QLD"]],
"4169":[["Kangaroo Point","QLD"],["East Brisbane","QLD"]],
"4170":[["Balmoral","QLD"],["Hawthorne","QLD"],["Morningside","QLD"],["Norman Park","QLD"]],
"4171":[["Balmoral","QLD"],["Bulimba","QLD"],["Hawthorne","QLD"]],
"4172":[["Murarrie","QLD"]],
"4173":[["Carindale","QLD"],["Tingalpa","QLD"]],
"4174":[["Hemmant","QLD"],["Lytton","QLD"],["Tingalpa","QLD"]],
"4179":[["Manly","QLD"],["Manly West","QLD"]],
// ── QLD — Gold Coast ──────────────────────────────────────────────────────────
"4209":[["Coomera","QLD"],["Upper Coomera","QLD"]],
"4210":[["Helensvale","QLD"],["Hope Island","QLD"]],
"4211":[["Arundel","QLD"],["Coomera","QLD"],["Labrador","QLD"],["Parkwood","QLD"]],
"4212":[["Currumbin","QLD"],["Tugun","QLD"]],
"4213":[["Mudgeeraba","QLD"],["Worongary","QLD"]],
"4214":[["Arundel","QLD"],["Labrador","QLD"]],
"4215":[["Southport","QLD"]],
"4216":[["Biggera Waters","QLD"],["Hollywell","QLD"],["Runaway Bay","QLD"]],
"4217":[["Broadbeach","QLD"],["Mermaid Beach","QLD"],["Surfers Paradise","QLD"]],
"4218":[["Broadbeach","QLD"],["Mermaid Waters","QLD"]],
"4219":[["Miami","QLD"],["Mermaid Beach","QLD"]],
"4220":[["Burleigh Heads","QLD"],["Burleigh Waters","QLD"]],
"4221":[["Burleigh Heads","QLD"],["Palm Beach","QLD"]],
"4223":[["Burleigh Heads","QLD"],["Tallebudgera","QLD"]],
"4224":[["Currumbin","QLD"],["Currumbin Waters","QLD"],["Palm Beach","QLD"]],
"4225":[["Bilinga","QLD"],["Coolangatta","QLD"],["Kirra","QLD"]],
"4226":[["Reedy Creek","QLD"],["Robina","QLD"]],
"4227":[["Elanora","QLD"],["Tallebudgera","QLD"]],
"4228":[["Currumbin Valley","QLD"],["Tallebudgera","QLD"]],
"4229":[["Robina","QLD"]],
"4230":[["Robina","QLD"]],
// ── QLD — Sunshine Coast ──────────────────────────────────────────────────────
"4551":[["Caloundra","QLD"]],
"4552":[["Caloundra West","QLD"]],
"4553":[["Caloundra West","QLD"],["Little Mountain","QLD"]],
"4556":[["Buderim","QLD"],["Mooloolaba","QLD"]],
"4557":[["Maroochydore","QLD"],["Mooloolaba","QLD"]],
"4558":[["Maroochydore","QLD"]],
"4559":[["Nambour","QLD"]],
"4560":[["Nambour","QLD"]],
"4562":[["Noosa Heads","QLD"],["Noosaville","QLD"],["Tewantin","QLD"]],
"4563":[["Cooroy","QLD"],["Noosa Heads","QLD"]],
"4564":[["Noosa Heads","QLD"]],
"4566":[["Noosaville","QLD"],["Tewantin","QLD"]],
"4567":[["Noosa Heads","QLD"],["Noosaville","QLD"]],
"4568":[["Pomona","QLD"],["Cooroy","QLD"]],
"4569":[["Gympie","QLD"]],
// ── QLD — Ipswich / Logan ─────────────────────────────────────────────────────
"4300":[["Booval","QLD"],["Ipswich","QLD"]],
"4301":[["Ipswich","QLD"],["Leichhardt","QLD"]],
"4304":[["Basin Pocket","QLD"],["Blackstone","QLD"],["Bundamba","QLD"]],
"4305":[["Ipswich","QLD"],["Silkstone","QLD"]],
"4306":[["Karalee","QLD"],["Lake Wivenhoe","QLD"]],
"4350":[["East Toowoomba","QLD"],["Newtown","QLD"],["South Toowoomba","QLD"],["Toowoomba","QLD"]],
"4351":[["Centenary Heights","QLD"],["Toowoomba","QLD"]],
// ── QLD — Cairns ─────────────────────────────────────────────────────────────
"4868":[["Cairns","QLD"],["Manoora","QLD"],["Manunda","QLD"]],
"4869":[["Bungalow","QLD"],["Cairns","QLD"]],
"4870":[["Cairns","QLD"],["Edge Hill","QLD"]],
"4871":[["Cairns","QLD"],["Manoora","QLD"]],
"4872":[["Atherton","QLD"]],
"4877":[["Port Douglas","QLD"]],
"4878":[["Cairns","QLD"]],
"4879":[["Palm Cove","QLD"]],
// ── QLD — Townsville ──────────────────────────────────────────────────────────
"4810":[["Townsville","QLD"],["North Ward","QLD"],["South Townsville","QLD"]],
"4811":[["Aitkenvale","QLD"],["Garbutt","QLD"],["Townsville","QLD"]],
"4812":[["Hermit Park","QLD"],["Hyde Park","QLD"],["Townsville","QLD"]],
"4814":[["Annandale","QLD"],["Kirwan","QLD"],["Townsville","QLD"]],
"4815":[["Mundingburra","QLD"],["Thuringowa","QLD"],["Townsville","QLD"]],
"4816":[["Townsville","QLD"]],
"4817":[["Bohle Plains","QLD"],["Kelso","QLD"],["Townsville","QLD"]],
// ── QLD — Mackay / Rockhampton ────────────────────────────────────────────────
"4700":[["Rockhampton","QLD"]],
"4701":[["Rockhampton","QLD"]],
"4740":[["Mackay","QLD"]],
"4741":[["Mackay","QLD"]],
// ── SA — Adelaide Metro ───────────────────────────────────────────────────────
"5000":[["Adelaide","SA"],["City","SA"]],
"5005":[["Adelaide","SA"]],
"5006":[["North Adelaide","SA"]],
"5007":[["Bowden","SA"],["Brompton","SA"]],
"5008":[["Croydon","SA"],["Devon Park","SA"],["Ridleyton","SA"]],
"5009":[["Beverley","SA"],["Pennington","SA"],["Woodville","SA"]],
"5010":[["Mansfield Park","SA"],["Wingfield","SA"],["Woodville","SA"]],
"5011":[["Hendon","SA"],["Royal Park","SA"],["Woodville","SA"]],
"5012":[["Pennington","SA"],["Queenstown","SA"]],
"5013":[["Birkenhead","SA"],["Ethelton","SA"],["Glanville","SA"],["Ottoway","SA"],["Peterhead","SA"]],
"5014":[["Alberton","SA"],["Port Adelaide","SA"],["Rosewater","SA"]],
"5015":[["Cleveland","SA"],["Port Adelaide","SA"],["Semaphore Park","SA"]],
"5016":[["Exeter","SA"],["Semaphore","SA"],["Semaphore South","SA"]],
"5017":[["Largs Bay","SA"],["Largs North","SA"],["Osborne","SA"]],
"5018":[["Outer Harbor","SA"],["Taperoo","SA"]],
"5019":[["Exeter","SA"],["Semaphore","SA"],["Taperoo","SA"]],
"5020":[["Fulham Gardens","SA"],["West Beach","SA"],["West Lakes","SA"]],
"5021":[["West Lakes Shore","SA"]],
"5022":[["Grange","SA"],["Henley Beach","SA"],["Henley Beach South","SA"]],
"5023":[["Flinders Park","SA"],["Kidman Park","SA"],["Seaton","SA"]],
"5024":[["Findon","SA"],["Flinders Park","SA"],["Woodville","SA"]],
"5025":[["Hindmarsh","SA"],["Welland","SA"]],
"5031":[["Mile End","SA"],["Thebarton","SA"],["Torrensville","VIC"]],
"5032":[["Brooklyn Park","SA"],["Lockleys","SA"],["Underdale","SA"]],
"5033":[["Cowandilla","SA"],["Hilton","SA"],["Marleston","SA"]],
"5034":[["Goodwood","SA"],["Millswood","SA"],["Wayville","SA"]],
"5035":[["Black Forest","SA"],["Clarence Park","SA"],["Forestville","SA"]],
"5036":[["Edwardstown","SA"],["Melrose Park","SA"]],
"5037":[["Ascot Park","SA"],["Marion","SA"],["Park Holme","SA"]],
"5038":[["Plympton","SA"],["Plympton Park","SA"]],
"5039":[["Mitcham","SA"],["Panorama","SA"]],
"5040":[["Clovelly Park","SA"],["Eden Hills","SA"],["Pasadena","SA"]],
"5041":[["Daw Park","SA"],["Melrose Park","SA"],["Westbourne Park","SA"]],
"5042":[["Coromandel Valley","SA"],["Flagstaff Hill","SA"],["Sheidow Park","SA"]],
"5043":[["Hallett Cove","SA"],["Sheidow Park","SA"],["Trott Park","SA"]],
"5044":[["Glenelg","SA"],["Glenelg East","SA"],["Glenelg South","SA"]],
"5045":[["Glenelg","SA"],["Glenelg North","SA"],["Somerton Park","SA"]],
"5046":[["Brighton","SA"],["Hove","SA"],["Kingston Park","SA"]],
"5047":[["Hove","SA"],["Marino","SA"],["Seacombe Gardens","SA"]],
"5048":[["Christies Beach","SA"],["Morphett Vale","SA"],["Noarlunga Downs","SA"]],
"5049":[["Christie Downs","SA"],["Christies Beach","SA"],["Noarlunga Centre","SA"]],
"5050":[["Belair","SA"],["Blackwood","SA"],["Eden Hills","SA"]],
"5051":[["Hawthorndene","SA"],["Mitcham","SA"]],
"5052":[["Coromandel East","SA"],["Coromandel Valley","SA"]],
"5061":[["Glenelg North","SA"],["Unley","SA"]],
"5062":[["Springfield","SA"],["Unley Park","SA"],["Wayville","SA"]],
"5063":[["Fullarton","SA"],["Hyde Park","SA"],["Highgate","SA"]],
"5064":[["Glen Osmond","SA"],["Glenunga","SA"],["Kingswood","SA"],["St Georges","SA"]],
"5065":[["Burnside","SA"],["Hazelwood Park","SA"],["Toorak Gardens","SA"]],
"5066":[["Beaumont","SA"],["Stonyfell","SA"],["Waterfall Gully","SA"]],
"5067":[["Evandale","SA"],["Norwood","SA"],["Beulah Park","SA"]],
"5068":[["College Park","SA"],["Evandale","SA"],["Kensington","SA"]],
"5069":[["Kent Town","SA"],["Norwood","SA"],["Rose Park","SA"]],
"5070":[["Felixstow","SA"],["Firle","SA"],["Glynde","SA"],["Hackney","SA"]],
"5071":[["Dulwich","SA"],["Leabrook","SA"],["Tusmore","SA"]],
"5072":[["Burnside","SA"],["Leabrook","SA"],["Wattle Park","SA"]],
"5073":[["Magill","SA"],["Tranmere","SA"],["Rosslyn Park","SA"]],
"5074":[["Campbelltown","SA"],["Newton","SA"],["Rostrevor","SA"]],
"5075":[["Dernancourt","SA"],["Hope Valley","SA"],["Modbury","SA"]],
"5081":[["Blair Athol","SA"],["Broadview","SA"],["Kilburn","SA"]],
"5082":[["Collinswood","SA"],["Fitzroy","SA"],["Prospect","SA"]],
"5083":[["Blair Athol","SA"],["Broadview","SA"],["Kilburn","SA"],["Prospect","SA"]],
"5084":[["Angle Park","SA"],["Mansfield Park","SA"],["Regency Park","SA"]],
"5085":[["Enfield","SA"],["Northfield","SA"],["Northgate","SA"]],
"5086":[["Clearview","SA"],["Greenacres","SA"],["Holden Hill","SA"]],
"5087":[["Hillcrest","SA"],["Para Hills","SA"],["Valley View","SA"]],
"5088":[["Marden","SA"],["Windsor Gardens","SA"],["Manningham","SA"]],
"5089":[["Highbury","SA"]],
"5090":[["Ridgehaven","SA"],["Tea Tree Gully","SA"]],
"5091":[["St Agnes","SA"],["Vista","SA"]],
"5092":[["Modbury Heights","SA"],["Modbury North","SA"],["Redwood Park","SA"]],
"5093":[["Ingle Farm","SA"],["Para Hills","SA"],["Para Hills West","SA"]],
"5094":[["Brahma Lodge","SA"],["Salisbury","SA"],["Salisbury East","SA"]],
"5095":[["Pooraka","SA"],["Salisbury","SA"],["Salisbury North","SA"]],
"5096":[["Parafield","SA"],["Parafield Gardens","SA"]],
"5097":[["Salisbury Downs","SA"],["Salisbury Heights","SA"]],
"5098":[["Paralowie","SA"],["Salisbury","SA"]],
"5106":[["Davoren Park","SA"],["Elizabeth","SA"],["Munno Para","SA"]],
"5107":[["Elizabeth","SA"],["Elizabeth Downs","SA"],["Elizabeth East","SA"]],
"5108":[["Elizabeth Park","SA"],["Elizabeth South","SA"],["Elizabeth Vale","SA"]],
"5109":[["Craigmore","SA"],["Munno Para West","SA"]],
"5110":[["Angle Vale","SA"],["Curtis","SA"],["Evanston","SA"]],
"5112":[["Andrews Farm","SA"],["Blakeview","SA"],["Smithfield","SA"]],
"5113":[["Blakeview","SA"],["Craigmore","SA"]],
"5114":[["Bibaringa","SA"],["Gould Creek","SA"],["Yatala Vale","SA"]],
// ── SA — Regional ─────────────────────────────────────────────────────────────
"5200":[["Strathalbyn","SA"]],
"5210":[["Victor Harbor","SA"]],
"5211":[["Goolwa","SA"],["Port Elliot","SA"]],
"5212":[["Goolwa","SA"]],
"5253":[["Murray Bridge","SA"]],
"5290":[["Mount Gambier","SA"]],
"5291":[["Mount Gambier","SA"]],
"5600":[["Whyalla","SA"]],
"5601":[["Whyalla","SA"]],
"5700":[["Port Augusta","SA"]],
"5701":[["Port Augusta","SA"]],
// ── WA — Perth Metro ─────────────────────────────────────────────────────────
"6000":[["Perth","WA"],["Perth City","WA"]],
"6003":[["East Perth","WA"],["Highgate","WA"],["Mount Lawley","WA"]],
"6004":[["East Perth","WA"]],
"6005":[["West Perth","WA"]],
"6006":[["North Perth","WA"]],
"6007":[["Leederville","WA"],["West Leederville","WA"]],
"6008":[["Claremont","WA"],["Cottesloe","WA"],["Peppermint Grove","WA"]],
"6009":[["Nedlands","WA"],["Shenton Park","WA"],["Subiaco","WA"]],
"6010":[["City Beach","WA"],["Floreat","WA"],["Wembley","WA"]],
"6011":[["Cottesloe","WA"],["Peppermint Grove","WA"]],
"6012":[["Mosman Park","WA"],["Peppermint Grove","WA"]],
"6014":[["Floreat","WA"],["Joondanna","WA"],["Mount Hawthorn","WA"]],
"6015":[["City Beach","WA"],["Floreat","WA"],["Hamersley","WA"]],
"6016":[["Glendalough","WA"],["Mount Hawthorn","WA"],["Osborne Park","WA"]],
"6017":[["Stirling","VIC"],["Karrinyup","WA"],["Osborne Park","WA"]],
"6018":[["Hamersley","WA"],["Innaloo","WA"],["Scarborough","WA"]],
"6019":[["Doubleview","WA"],["Scarborough","WA"]],
"6020":[["Carine","WA"],["Gwelup","WA"],["Karrinyup","WA"]],
"6021":[["Balga","WA"],["Westminster","WA"]],
"6022":[["Balga","WA"],["Nollamara","WA"]],
"6023":[["Duncraig","WA"],["Greenwood","WA"]],
"6024":[["Craigie","WA"],["Greenwood","WA"],["Padbury","WA"]],
"6025":[["Currambine","WA"],["Heathridge","WA"],["Ocean Reef","WA"]],
"6026":[["Beldon","WA"],["Edgewater","WA"],["Woodvale","WA"]],
"6027":[["Connolly","WA"],["Joondalup","WA"],["Kinross","WA"]],
"6028":[["Burns Beach","WA"],["Iluka","WA"],["Currambine","WA"]],
"6030":[["Clarkson","WA"],["Merriwa","WA"],["Mindarie","WA"],["Quinns Rocks","WA"]],
"6031":[["Butler","WA"],["Ridgewood","WA"],["Tapping","WA"]],
"6032":[["Banksia Grove","WA"],["Gnangara","WA"]],
"6034":[["Carabooda","WA"],["Pinjar","WA"],["Wanneroo","WA"]],
"6035":[["Alkimos","WA"],["Eglinton","WA"],["Yanchep","WA"]],
"6036":[["Neerabup","WA"],["Two Rocks","WA"]],
"6050":[["Bassendean","WA"],["Morley","WA"],["Noranda","WA"]],
"6051":[["Bayswater","WA"],["Morley","WA"]],
"6052":[["Bedford","WA"],["Inglewood","WA"],["Noranda","WA"]],
"6053":[["Bayswater","WA"],["Maylands","WA"]],
"6054":[["Ashfield","WA"],["Bassendean","WA"]],
"6055":[["Bayswater","WA"],["Morley","WA"],["Noranda","WA"]],
"6056":[["Herne Hill","WA"],["Midland","WA"],["Middle Swan","WA"]],
"6057":[["Bellevue","WA"],["Midvale","WA"],["Swan View","WA"]],
"6059":[["Balga","WA"],["Girrawheen","WA"],["Koondoola","WA"]],
"6060":[["Hamersley","WA"],["Tuart Hill","WA"],["Yokine","WA"]],
"6061":[["Balga","WA"],["Girrawheen","WA"],["Westminster","WA"]],
"6062":[["Beechboro","WA"],["Caversham","WA"],["Eden Hill","WA"]],
"6063":[["Bennett Springs","WA"],["Lockridge","WA"],["Malaga","WA"]],
"6064":[["Alexander Heights","WA"],["Ballajura","WA"],["Koondoola","WA"],["Mirrabooka","WA"]],
"6065":[["Hocking","WA"],["Madeley","WA"],["Nollamara","WA"],["Wanneroo","WA"]],
"6066":[["Darch","WA"],["Pearsall","WA"],["Wangara","WA"]],
"6067":[["Landsdale","WA"],["Lexia","WA"]],
"6068":[["Caversham","WA"],["Upper Swan","WA"]],
"6069":[["Ellenbrook","WA"],["The Vines","WA"]],
"6070":[["Darlington","WA"],["Glen Forrest","WA"],["Mahogany Creek","WA"]],
"6071":[["Bickley","WA"],["Carmel","WA"],["Kalamunda","WA"],["Lesmurdie","WA"]],
"6076":[["Forrestfield","WA"],["High Wycombe","WA"],["Maida Vale","WA"]],
"6082":[["Mundaring","WA"]],
"6083":[["Mount Helena","WA"],["Sawyers Valley","WA"]],
"6100":[["Burswood","WA"],["Lathlain","WA"],["Victoria Park","WA"]],
"6101":[["Carlisle","WA"],["Lathlain","WA"],["Victoria Park","WA"]],
"6102":[["Bentley","WA"],["Carlisle","WA"],["East Cannington","WA"]],
"6103":[["Rivervale","WA"]],
"6104":[["Cloverdale","WA"],["Redcliffe","WA"],["Rivervale","WA"]],
"6105":[["Ascot","WA"],["Redcliffe","WA"]],
"6106":[["Belmont","WA"],["South Guildford","WA"]],
"6107":[["Cannington","WA"],["East Cannington","WA"],["Queens Park","WA"]],
"6108":[["East Cannington","WA"],["Welshpool","WA"]],
"6109":[["Beckenham","WA"],["Kenwick","WA"]],
"6110":[["Armadale","WA"],["Camillo","WA"],["Kelmscott","WA"]],
"6111":[["Armadale","WA"],["Kelmscott","WA"],["Oakford","WA"]],
"6112":[["Champion Lakes","WA"],["Harrisdale","WA"],["Piara Waters","WA"]],
"6147":[["Lynwood","WA"],["Parkwood","WA"],["Riverton","WA"]],
"6148":[["Ferndale","WA"],["Riverton","WA"],["Rossmoyne","WA"]],
"6149":[["Leeming","WA"],["Willetton","WA"]],
"6150":[["Bull Creek","WA"],["Leeming","WA"],["Murdoch","WA"]],
"6151":[["Applecross","WA"],["Ardross","WA"],["Mount Pleasant","WA"]],
"6152":[["Bateman","WA"],["Kardinya","WA"],["Murdoch","WA"]],
"6153":[["Attadale","WA"],["Bicton","WA"],["Myaree","WA"]],
"6154":[["Alfred Cove","WA"],["Myaree","WA"],["Palmyra","WA"]],
"6155":[["Canning Vale","WA"],["Piara Waters","WA"]],
"6156":[["Fremantle","WA"],["O'Connor","WA"],["White Gum Valley","WA"]],
"6157":[["East Fremantle","WA"],["Fremantle","WA"]],
"6158":[["Hamilton Hill","WA"],["North Coogee","WA"],["South Fremantle","WA"]],
"6159":[["Beaconsfield","WA"],["Fremantle","WA"],["White Gum Valley","WA"]],
"6160":[["Fremantle","WA"],["Hilton","WA"]],
"6161":[["Bibra Lake","WA"],["Coolbellup","WA"],["North Lake","WA"]],
"6162":[["Coolbellup","WA"],["Spearwood","WA"],["Success","WA"]],
"6163":[["Munster","WA"],["Spearwood","WA"],["Yangebup","WA"]],
"6164":[["Atwell","WA"],["Aubin Grove","WA"],["Banjup","WA"]],
"6165":[["Banksia Beach","WA"],["Safety Bay","WA"],["Secret Harbour","WA"]],
"6166":[["Kwinana","WA"],["Mandogalup","WA"]],
"6167":[["Casuarina","WA"],["Kwinana","WA"],["Leda","WA"],["Parmelia","WA"]],
"6168":[["Baldivis","WA"],["Kwinana","WA"],["Wellard","WA"]],
"6169":[["Baldivis","WA"],["Golden Bay","WA"],["Singleton","WA"]],
"6170":[["Mandurah","WA"],["Rockingham","WA"]],
"6171":[["Rockingham","WA"],["Safety Bay","WA"],["Waikiki","WA"]],
"6172":[["Port Kennedy","WA"],["Rockingham","WA"],["Waikiki","WA"]],
"6173":[["Cooloongup","WA"],["Warnbro","WA"]],
"6174":[["Baldivis","WA"],["Karnup","WA"]],
"6175":[["Baldivis","WA"],["Bertram","WA"],["Wellard","WA"]],
"6208":[["Mandurah","WA"],["Madora Bay","WA"],["Meadow Springs","WA"]],
"6210":[["Mandurah","WA"]],
"6211":[["Mandurah","WA"],["Wannanup","WA"]],
"6230":[["Bunbury","WA"]],
"6231":[["Bunbury","WA"]],
// ── WA — Regional ─────────────────────────────────────────────────────────────
"6330":[["Albany","WA"]],
"6430":[["Kalgoorlie","WA"]],
"6431":[["Boulder","WA"],["Kalgoorlie","WA"]],
"6530":[["Geraldton","WA"]],
"6532":[["Geraldton","WA"],["Mahomets Flats","WA"]],
// ── TAS — Hobart Metro ────────────────────────────────────────────────────────
"7000":[["Hobart","TAS"],["Battery Point","TAS"],["Glebe","TAS"]],
"7004":[["Sandy Bay","TAS"]],
"7005":[["Battery Point","TAS"],["South Hobart","TAS"]],
"7007":[["Lenah Valley","TAS"],["West Hobart","TAS"]],
"7008":[["Derwent Park","TAS"],["Lutana","TAS"],["Moonah","TAS"]],
"7009":[["Glenorchy","TAS"],["Montrose","TAS"]],
"7010":[["Claremont","TAS"],["Glenorchy","TAS"]],
"7011":[["Berriedale","TAS"],["Claremont","TAS"],["Chigwell","TAS"]],
"7012":[["Austins Ferry","TAS"],["Granton","TAS"],["Pontville","TAS"]],
"7015":[["Bellerive","TAS"],["Clarence","TAS"],["Montagu Bay","TAS"]],
"7016":[["Bellerive","TAS"],["Howrah","TAS"],["Rokeby","TAS"]],
"7018":[["Bellerive","TAS"],["Howrah","TAS"],["Rokeby","TAS"],["Rosny","TAS"]],
"7019":[["Rokeby","TAS"]],
"7020":[["Lauderdale","TAS"],["Ralphs Bay","TAS"]],
"7021":[["Sorell","TAS"]],
"7050":[["Kingston","TAS"],["Blackmans Bay","TAS"]],
"7052":[["Blackmans Bay","TAS"],["Kettering","TAS"]],
"7053":[["Taroona","TAS"]],
"7054":[["Fern Tree","TAS"],["Ridgeway","TAS"]],
"7055":[["Kingston","TAS"],["Kingston Beach","TAS"]],
// ── TAS — Launceston ─────────────────────────────────────────────────────────
"7248":[["Prospect","TAS"],["Launceston","TAS"]],
"7249":[["Launceston","TAS"],["Newstead","TAS"]],
"7250":[["Launceston","TAS"],["Invermay","TAS"],["Mowbray","TAS"]],
"7251":[["Newnham","TAS"],["Launceston","TAS"]],
"7252":[["Beaconsfield","TAS"],["Karoola","TAS"]],
"7253":[["George Town","TAS"]],
// ── TAS — Regional ────────────────────────────────────────────────────────────
"7310":[["Devonport","TAS"]],
"7315":[["Ulverstone","TAS"]],
"7320":[["Burnie","TAS"],["Wynyard","TAS"]],
"7321":[["Burnie","TAS"]],
"7325":[["Somerset","TAS"],["Wynyard","TAS"]],
// ── NT — Darwin Metro ─────────────────────────────────────────────────────────
"0800":[["Darwin","NT"]],
"0801":[["Darwin","NT"]],
"0802":[["Darwin","NT"]],
"0810":[["Casuarina","NT"],["Darwin","NT"],["Jingili","NT"],["Moil","NT"]],
"0811":[["Coconut Grove","NT"],["Fannie Bay","NT"],["Nightcliff","NT"],["Rapid Creek","NT"]],
"0812":[["Buffalo Creek","NT"],["Holmes","NT"],["Leanyer","NT"],["Malak","NT"],["Nakara","NT"],["Northlakes","NT"],["Wanguri","NT"],["Anula","NT"]],
"0813":[["Brinkin","NT"],["Casuarina","NT"],["Lyons","NT"],["Tiwi","NT"],["Wagaman","NT"]],
"0820":[["Darwin","NT"],["Stuart Park","NT"],["Woolner","NT"]],
"0821":[["Bayview","NT"],["Darwin","NT"],["East Point","NT"],["Fannie Bay","NT"]],
"0822":[["Darwin","NT"],["Larrakeyah","NT"],["The Gardens","NT"]],
"0828":[["Berrimah","NT"],["Darwin","NT"]],
"0829":[["Humpty Doo","NT"],["Virginia","NT"]],
"0830":[["Palmerston","NT"]],
"0831":[["Bakewell","NT"],["Durack","NT"],["Gunn","NT"],["Johnston","NT"],["Palmerston","NT"],["Zuccoli","NT"]],
"0832":[["Howard Springs","NT"],["Palmerston","NT"]],
"0835":[["Girraween","NT"],["Pinelands","NT"],["Virginia","NT"]],
// ── NT — Alice Springs ────────────────────────────────────────────────────────
"0870":[["Alice Springs","NT"]],
"0871":[["Alice Springs","NT"]],
"0872":[["Alice Springs","NT"]],
};
